const translations: Record<string, string> = {
  FLB_BRAND_ALT: 'Ksisters',
  FLB_CIRCULATION_DESCRIPTION: 'FAT LAB працює не просто як ще один засіб для гладкості шкіри. Патч створює локальне тепло й підтримує мікроциркуляцію саме в тій зоні, якій хочеться приділити більше уваги.',
  FLB_CIRCULATION_FLOW_DESCRIPTION: 'підтримує активність у зоні догляду',
  FLB_CIRCULATION_FLOW_TITLE: 'Мікроциркуляція',
  FLB_CIRCULATION_LEAD: 'Живіт, руки, стегна чи ноги — ти сама обираєш, де працює патч.',
  FLB_CIRCULATION_MODEL_ALT: 'Жінка з патчем FAT LAB на руці',
  FLB_CIRCULATION_RESULT_DESCRIPTION: 'допомагає шкірі виглядати більш гладенькою та пружною',
  FLB_CIRCULATION_RESULT_TITLE: 'Видимий результат',
  FLB_CIRCULATION_TEMPERATURE_DESCRIPTION: 'допомагає зігріти зону нанесення',
  FLB_CIRCULATION_TEMPERATURE_TITLE: 'М’яке тепло',
  FLB_CIRCULATION_TITLE: 'Гладкість починається з мікроциркуляції',
  FLB_HEAT_AFTER: 'Через 4 години',
  FLB_HEAT_AFTER_ALT: 'Термографічне зображення через чотири години використання патча',
  FLB_HEAT_BEFORE: 'До використання',
  FLB_HEAT_BEFORE_ALT: 'Термографічне зображення до використання патча',
  FLB_HEAT_DESCRIPTION_1: 'У патчі поєднали графенову сітку та турмалін, які допомагають м’яко й рівномірно прогрівати зону нанесення.',
  FLB_HEAT_DESCRIPTION_2: 'Тому під час використання ти поступово відчуваєш тепло, а патч підтримує мікроциркуляцію саме там, де працює.',
  FLB_HEAT_MODEL_ALT: 'Патч FAT LAB на животі',
  FLB_HEAT_NOTE: '*За результатами human application test.\nІндивідуальні результати можуть відрізнятися',
  FLB_HEAT_STAT_FLOW_LABEL: 'показника мікроциркуляції після одного використання*',
  FLB_HEAT_STAT_FLOW_VALUE: '+111,45%',
  FLB_HEAT_STAT_TEMP_LABEL: 'зміна температури поверхні шкіри після одного використання*',
  FLB_HEAT_STAT_TEMP_VALUE: '+4,17 °C',
  FLB_HEAT_TITLE: 'Тепло, яке працює на результат',
  FLB_RESULTS_TITLE: 'Більше гладкості\n— і це помітно',
  FLB_RESULTS_DESCRIPTION: 'Гладкіша шкіра, менше помітних нерівностей і набряклості\n— саме такі зміни відзначили учасники тестування FAT LAB',
  FLB_RESULTS_STAT_1_VALUE: '-19,1%',
  FLB_RESULTS_STAT_1_LABEL: 'видимості целюліту після\n8 тижнів*',
  FLB_RESULTS_STAT_2_VALUE: '100%',
  FLB_RESULTS_STAT_2_LABEL: 'учасників зазначили, що целюліт\nстав менш помітним**',
  FLB_RESULTS_STAT_3_VALUE: '95%',
  FLB_RESULTS_STAT_3_LABEL: 'помітили, що шкіра на стегнах і\nвнутрішній стороні рук виглядає\nбільш пружною**',
  FLB_RESULTS_STAT_4_VALUE: '95%',
  FLB_RESULTS_STAT_4_LABEL: 'відзначили меншу\nнабряклість литок**',
  FLB_RESULTS_NOTE: '*За результатами human application test.\n**За результатами самооцінки учасників після 4 та 8 тижнів. Індивідуальні результати можуть відрізнятися.',
  FLB_INGREDIENTS_TITLE: 'Отримай більше, ніж просто warming-ефект',
  FLB_INGREDIENTS_DESCRIPTION: 'Поки технологія патчу працює зовні, комплекс компонентів доповнює догляд за шкірою зсередини самої формули',
  FLB_INGREDIENTS_CAFFEINE_TITLE: 'КОФЕЇН',
  FLB_INGREDIENTS_CAFFEINE_DESCRIPTION: 'Допомагає тонізувати шкіру та підтримувати мікроциркуляцію',
  FLB_INGREDIENTS_CAPSICUM_TITLE: 'CAPSICUM',
  FLB_INGREDIENTS_CAPSICUM_DESCRIPTION: 'Саме він додає те характерне відчуття м’якого тепла',
  FLB_INGREDIENTS_PEPTIDES_TITLE: 'ПЕПТИДИ',
  FLB_INGREDIENTS_PEPTIDES_DESCRIPTION: 'Доповнюють догляд, спрямовані на більш пружний вигляд шкіри',
  FLB_INGREDIENTS_GREEN_TEA_TITLE: 'ЗЕЛЕНИЙ ЧАЙ',
  FLB_INGREDIENTS_GREEN_TEA_DESCRIPTION: 'Дає антиоксидантну підтримку та допомагає зберігати відчуття доглянутості',
  FLB_INGREDIENTS_BROMELAIN_TITLE: 'БРОМЕЛАЇН',
  FLB_INGREDIENTS_BROMELAIN_DESCRIPTION: 'Ключовий компонент FAT LAB для догляду за зонами, схильними до набряклості та нерівностей',
  FLB_SAFETY_TITLE: 'Важливо! Трохи тепла — ок. Сильне печіння — ні.',
  FLB_SAFETY_DESCRIPTION: 'Під час використання можна відчувати тепло або легке поколювання. Якщо відчуття стають надто інтенсивними чи з’являється дискомфорт, зніми патч.\nДля чутливої шкіри рекомендуємо спочатку протестувати його на невеликій ділянці.',
  FLB_ZONES_TITLE: 'Обирай зону.\nПатч зробить решту.',
  FLB_ZONES_DESCRIPTION: 'Впиши догляд саме в ту частину body routine,\nяка потрібна тобі сьогодні',
  FLB_ZONES_ARMS: 'Руки та плечі',
  FLB_ZONES_HIPS: 'Стегна та сідниці',
  FLB_ZONES_CALVES: 'Литки та щиколотки',
  FLB_ZONES_WAIST: 'Талія й низ живота',
  FLB_ZONES_FOOTNOTE: 'Наклей саме там, де сьогодні потрібен твій body-care focus',
  FLB_SAFETY_MODEL_ALT: 'Патч FAT LAB на тілі',
  FLB_USAGE_TITLE: 'Наклей — і дозволь патчу працювати',
  FLB_USAGE_STEP_LABEL: 'крок',
  FLB_USAGE_STEP_1_TITLE: 'Підготуй шкіру',
  FLB_USAGE_STEP_1_DESCRIPTION: 'Очисть потрібну зону та переконайся, що шкіра суха',
  FLB_USAGE_STEP_2_TITLE: 'Наклей патч',
  FLB_USAGE_STEP_2_DESCRIPTION: 'Зніми захисну плівку, приклади патч до шкіри та добре притисни',
  FLB_USAGE_STEP_3_TITLE: 'Залиш на 4–8 годин',
  FLB_USAGE_STEP_3_DESCRIPTION: 'Носи його вдень або залиш на ніч — як зручніше тобі',
  FLB_USAGE_SCHEDULE_TITLE: 'Як часто використовувати?',
  FLB_USAGE_SCHEDULE_DESCRIPTION: 'Для регулярного догляду бренд рекомендує використовувати FAT LAB через день протягом 3–4 тижнів',
  FLB_USAGE_DAY_1: 'День 1',
  FLB_USAGE_DAY_2: 'День 2',
  FLB_USAGE_DAY_3: 'День 3',
  FLB_USAGE_DAY_4: 'День 4',
  FLB_USAGE_DAY_5: 'День 5',
  FLB_USAGE_DAY_6: 'День 6',
  FLB_USAGE_DAY_7: 'День 7',
  FLB_USAGE_DAY_ON: 'День із патчем',
  FLB_USAGE_DAY_OFF: 'Перерва',
  FLB_USAGE_NOTE: 'ВАЖЛИВО: не наклеюй патч одразу після гарячого душу, гоління чи ексфоліації!',
  FLB_FINAL_TITLE: 'Body care, для якої не треба знаходити час',
  FLB_FINAL_SUBTITLE: 'Наклей патч перед роботою, серіалом або сном — і продовжуй свій день',
  FLB_FINAL_BENEFIT_1: 'Без масажу',
  FLB_FINAL_BENEFIT_2: 'без змивання',
  FLB_FINAL_BENEFIT_3: 'Без ще одного складного ритуалу',
  FLB_FINAL_PACK_TITLE: '8 патчів у коробці',
  FLB_FINAL_PACK_DESCRIPTION: 'Достатньо, щоб почати знайомство з FAT LAB і додати технологічний корейський body care у свою рутину.',
  FLB_FINAL_LEAD: 'Просто обираєш зону — решта вже справа FAT LAB',
  FLB_FINAL_PRODUCT_ALT: 'Упаковка FAT LAB Bromelain Microcirculation Patch',
  FLB_HERO_DESCRIPTION: 'FAT LAB — це патчі з бромелаїном і технологією м’якого тепла. Вони підтримують мікроциркуляцію, допомагають зменшити видимість целюліту й набряклості та зробити шкіру більш гладенькою і пружною',
  FLB_HERO_DURATION: '4–8 годин догляду',
  FLB_HERO_IMAGE_ALT: 'Патчі FAT LAB Bromelain Microcirculation Patch в упаковці',
  FLB_HERO_INSTRUCTION: 'Просто наклей патч на потрібну зону на 4–8 годин\n— і займайся своїми справами.',
  FLB_HERO_PACK: '8 патчів в упаковці',
  FLB_HERO_SUBTITLE: 'Менше нерівностей. Більше гладкості. Один патч.',
  FLB_HERO_TITLE: 'FAT LAB Bromelain Microcirculation Patch',
};

export default translations;
